-- BORRADO PRODUCTOS
DECLARE 
TYPE c1 IS TABLE OF SIEBEL.EIM_FN_ASSET.AST_BU%TYPE;
TYPE c2 IS TABLE OF SIEBEL.EIM_FN_ASSET.AST_PROD_BU%TYPE;
TYPE c3 IS TABLE OF SIEBEL.EIM_FN_ASSET.AST_PROD_NAME%TYPE;
TYPE c4 IS TABLE OF SIEBEL.EIM_FN_ASSET.AST_ASSET_NUM%TYPE;
TYPE c5 IS TABLE OF SIEBEL.EIM_FN_ASSET.AST_REV_NUM%TYPE;
TYPE c10 IS TABLE OF SIEBEL.EIM_FN_ASSET.IF_ROW_STAT%TYPE;
TYPE c11 IS TABLE OF SIEBEL.EIM_FN_ASSET.IF_ROW_BATCH_NUM%TYPE;
TYPE c12 IS TABLE OF SIEBEL.EIM_FN_ASSET.ROW_ID%TYPE;


v_c1   c1; 
v_c2   c2; 
v_c3   c3; 
v_c4   c4; 
v_c5   c5; 
v_c10  c10;
v_c11  c11;
v_c12  c12;

contador NUMBER := 1000;

cursor datos_prod is
SELECT 'Default Organization' AST_BU,
       'Default Organization' AST_PROD_BU,
       i.name,s.ASSET_NUM,
       s.REV_NUM,
       'FOR_IMPORT' IF_ROW_STAT ,
       CEIL(ROWNUM/20000)+1400200000-1 IF_ROW_BATCH_NUM ,
       ROWNUM ROW_ID
  FROM SIEBEL.S_ASSET S
      ,SIEBEL.S_PROD_INT I
  WHERE s.prod_id = i.row_id(+)
   AND S.ASSET_NUM IN (
   '50030040260',
'45030026392',
'00130115108',
'11330012730',
'00130213572'
   ); -- Seleccionar producto

BEGIN
  OPEN datos_prod;
   LOOP
      FETCH datos_prod BULK COLLECT INTO v_c1,v_c2,v_c3,v_c4,v_c5,v_c10,v_c11,v_c12 LIMIT contador;

      FORALL I IN 1 .. v_c12.COUNT 
          INSERT INTO SIEBEL.EIM_FN_ASSET(AST_BU,AST_PROD_BU,AST_PROD_NAME,AST_ASSET_NUM,AST_REV_NUM,IF_ROW_STAT,IF_ROW_BATCH_NUM,ROW_ID )
          VALUES (v_c1(i),v_c2(i),v_c3(i),v_c4(i),v_c5(i),v_c10(i),v_c11(i),v_c12(i));
          
      EXIT WHEN datos_prod%NOTFOUND;
      COMMIT;
   END LOOP;
     
  CLOSE datos_prod;
END
;

-- VALIDAR TABLAS EIM
SELECT IF_ROW_STAT, AST_ASSET_NUM, IF_ROW_BATCH_NUM
FROM SIEBEL.EIM_FN_ASSET
WHERE 1 = 1
AND IF_ROW_BATCH_NUM BETWEEN 1400200000 AND 1400299999
;

