-- INSERT PN
SELECT 
'INSERT INTO SIEBEL.EIM_CONTACT3 (PARTY_TYPE_CD,PARTY_UID,CON_BU,CON_PRIV_FLG,CON_PERSON_UID,ADDR_COMMMEDIUM_CD,ADDR_NAME,CON_PR_EMAIL_ADDR,ADDR_COMMUSETYPECD,ADDR_ADDR,ADDR_X_OCS_STATUS,ADDR_X_OCS_ENDDATE,ADDRXOCSQUALIFICAT,ADDR_XOCSSTARTDATE,ADDRXOCSUSERAPPCRE,ADDRXOCSUSERAPPUPD,ADDRXOCSSOURCECREA,ADDRXOCSSOURCELAST,IF_ROW_STAT,IF_ROW_BATCH_NUM,ROW_ID) VALUES (''Person'','''||E.ID_TP_CD || E.ref_num||''','''||'Default Organization'||''','''||'N'||''','''||E.ID_TP_CD || E.ref_num||''','''||'Email'||''','''||B.NAME||'/'||TO_CHAR(D.START_DT, 'HH24:MM')||''','''||D.PREFERRED_IND||''','''||B.NAME ||''','''||C.REF_NUM ||''','''||'Y'||''','''||''||''','''||''||''','''||TO_CHAR(D.START_DT , 'DD/MM/YY HH24:MM:SS')||''','''||'EVELEZ/MAN-SER-060'||''','''||'EVELEZ/MAN-SER-060'||''','''||TO_CHAR(D.START_DT , 'DD/MM/YY HH24:MM:SS')||''','''||TO_CHAR(A.LAST_UPDATE_DT, 'DD/MM/YY HH24:MM:SS')||''','''||'FOR_IMPORT'||''','''||(CEIL(ROWNUM/20000)+300800000-1)||''','''||ROWNUM||''');'
FROM ADMMDM.CONTACTMETHODGROUP A
LEFT JOIN ADMMDM.CONTACTMETHOD C ON A.CONTACT_METHOD_ID = C.CONTACT_METHOD_ID
LEFT JOIN ADMMDM.CDCONTMETHTP B ON A.CONT_METH_TP_CD = B.CONT_METH_TP_CD AND C.CONT_METH_CAT_CD = B.CONT_METH_CAT_CD
LEFT JOIN ADMMDM.LOCATIONGROUP D ON A.LOCATION_GROUP_ID = D.LOCATION_GROUP_ID
LEFT JOIN ADMMDM.IDENTIFIER E ON D.CONT_ID = E.CONT_ID
WHERE c.CONT_METH_CAT_CD = '1200000' -- Solo correos electronicos
AND E.REF_NUM = '52736252' -- Buscar por documento
;

--INSERT PJ
SELECT 
'INSERT INTO SIEBEL.EIM_ACCNT_DTL (PARTY_TYPE_CD,PARTY_UID,ACCNT_BI,ACCNT_BU,LOC,NAME,XM_TYPE,XM_NAME,XM_ATTRIB_52,X_OCS_PR_EMAIL,EXT_ATTRIB_06,EXT_ATTRIB_08,EXT_ATTRIB_12,EXT_ATTRIB_07,EXT_ATTRIB_32,XM_ATTRIB_51,XMXOCSUSERAPPUPDAT,EXT_ATTRIB_31,EXT_ATTRIB_33,IF_ROW_STAT,IF_ROW_BATCH_NUM,ROW_ID) VALUES (''Organization'','''||E.ID_TP_CD || E.ref_num||''','''||'0-R9NH'||''','''||'Default Organization'||''','''||''||''','''||E.ID_TP_CD || E.ref_num||''','''||'CONTACTMETHODEMAIL'||''','''||B.NAME||'/'||TO_CHAR(D.START_DT, 'HH24:MM')||''','''||C.REF_NUM ||''','''||D.PREFERRED_IND||''','''||B.NAME ||''','''||'Y'||''','''||TO_CHAR(D.END_DT , 'DD/MM/YY HH24:MM:SS')||''','''||''||''','''||TO_CHAR(D.START_DT , 'DD/MM/YY HH24:MM:SS')||''','''||'EVELEZ/MAN-SER-060'||''','''||'EVELEZ/MAN-SER-060'||''','''||TO_CHAR(D.START_DT, 'DD/MM/YY HH24:MM:SS')||''','''||TO_CHAR(D.LAST_UPDATE_DT, 'DD/MM/YY HH24:MM:SS')||''','''||'FOR_IMPORT'||''','''||(CEIL(ROWNUM/20000)+400700000-1)||''','''||ROWNUM||''');'
FROM ADMMDM.CONTACTMETHODGROUP A
LEFT JOIN ADMMDM.CONTACTMETHOD C ON A.CONTACT_METHOD_ID = C.CONTACT_METHOD_ID
LEFT JOIN ADMMDM.CDCONTMETHTP B ON A.CONT_METH_TP_CD = B.CONT_METH_TP_CD AND C.CONT_METH_CAT_CD = B.CONT_METH_CAT_CD
LEFT JOIN ADMMDM.LOCATIONGROUP D ON A.LOCATION_GROUP_ID = D.LOCATION_GROUP_ID
LEFT JOIN ADMMDM.IDENTIFIER E ON D.CONT_ID = E.CONT_ID
WHERE c.CONT_METH_CAT_CD = '1200000' -- Solo correos electronicos
AND E.REF_NUM = '830062000' -- Buscar por documento
;