------------------ VALIDAR PERSONAS NATURALES ------------------------------
SELECT DISTINCT
D.HIGH AS TYPE_DOC,
A.X_OCS_ID_NUM AS NUM_DOC,
A.FST_NAME ||' '||A.MID_NAME ||' '|| A.LAST_NAME ||' '|| A.MAIDEN_NAME AS NOMBRE,
--A.CREATED,
E.DESC_TEXT as ESTADO,
A.LAST_UPD AS FECHA_ACT --Fecha actualización 
--B.X_OCS_PHONE_NUM,
FROM SIEBEL.S_CONTACT A
LEFT JOIN SIEBEL.S_LST_OF_VAL D ON a.X_OCS_ID_TYPE = D.NAME
LEFT JOIN SIEBEL.S_LST_OF_VAL E ON a.CUST_STAT_CD = E.VAL
WHERE 1=1
AND E.TYPE = 'ACCOUNT_STATUS'
AND D.TYPE = 'OCS_NID_TYPES'
AND A.X_OCS_ID_num IN ('52736252')---- CLIENTE REFERENTE
;

--------------- VALIDAR PERSONAS JURIDICAS -----------------
SELECT distinct
D.HIGH AS TYPE_DOC,
A.X_OCS_REF_NUM AS NUM_IDENT,
A.DESC_TEXT AS RAZON_SOCIAL,
E.DESC_TEXT as ESTADO,
--B.X_OCS_PHONE_NUM AS TELEFONO,
--B.X_OCS_AREA_CODE,
A.LAST_UPD AS FECHA_ACT
FROM SIEBEL.S_ORG_EXT A
LEFT JOIN SIEBEL.S_ORG_EXT_XM C ON A.ROW_ID = C.PAR_ROW_ID
--LEFT JOIN SIEBEL.S_ORG_PHONE B ON A.PAR_ROW_ID = B.ORG_ID
LEFT JOIN SIEBEL.S_LST_OF_VAL D ON a.X_OCS_ID_TP_CD = D.NAME
LEFT JOIN SIEBEL.S_LST_OF_VAL E ON a.CUST_STAT_CD = E.VAL
WHERE 1=1
AND E.TYPE = 'ACCOUNT_STATUS'
AND D.TYPE = 'OCS_NID_TYPES'
AND A.X_OCS_REF_NUM IN ('') -- Busacar por número documento
ORDER BY A.LAST_UPD DESC;



-------------------- METODOS DE CONTACTO PN --------------------------------
-- CORREOS PN
SELECT 
    TIP_ID.HIGH AS TIPO_DOC,
    B.X_OCS_ID_NUM as DOC_USUARIO,
    CASE WHEN B.PR_EMAIL_ADDR_ID = A.ROW_ID THEN 'Y' ELSE 'N' END AS PRINCIPAL,
    A.COMM_USE_TYPE_CD AS TIPO_USO,
    A.ADDR AS CORREO,
    a.LAST_UPD AS FECHA_ACTUALIZACION
FROM SIEBEL.S_PER_COMM_ADDR A
LEFT JOIN SIEBEL.S_CONTACT B ON A.PER_ID = B.ROW_ID
LEFT JOIN (SELECT DISTINCT S_LST_OF_VAL.NAME,S_LST_OF_VAL.DESC_TEXT DESCRIP,S_LST_OF_VAL.HIGH FROM SIEBEL.S_LST_OF_VAL S_LST_OF_VAL WHERE 1 = 1 AND S_LST_OF_VAL.TYPE LIKE '%OCS_NID_TYPES%' AND S_LST_OF_VAL.LANG_ID = 'ESN' AND S_LST_OF_VAL.ACTIVE_FLG = 'Y' AND S_LST_OF_VAL.NAME LIKE '%100%' AND S_LST_OF_VAL.HIGH IS NOT NULL) TIP_ID ON B.X_OCS_ID_TYPE=TIP_ID.NAME
where 1 = 1
    AND B.X_OCS_ID_NUM = '52736252' --Buscar por documento
;

-------------------- METODOS DE CONTACTO PJ --------------------------------
-- CORREOS PJ 
SELECT 
    TIP_ID.HIGH AS TIPO_DOC,
    A.X_OCS_REF_NUM as DOC_USUARIO,
    CASE WHEN A.X_OCS_PR_EMAIL_ID = B.ROW_ID THEN 'Y' ELSE 'N' END AS PRINCIPAL,
    B.ATTRIB_06 AS TIPO_USO,
    B.ATTRIB_52 AS CORREO_ELECTRONICO,
    B.LAST_UPD AS FECHA_ACTUALIZACION
FROM
    SIEBEL.S_ORG_EXT A
    LEFT JOIN SIEBEL.S_ORG_EXT_XM B ON A.ROW_ID = B.PAR_ROW_ID
    LEFT JOIN (SELECT DISTINCT S_LST_OF_VAL.NAME,S_LST_OF_VAL.DESC_TEXT DESCRIP,S_LST_OF_VAL.HIGH FROM SIEBEL.S_LST_OF_VAL S_LST_OF_VAL WHERE 1 = 1 AND S_LST_OF_VAL.TYPE LIKE '%OCS_NID_TYPES%' AND S_LST_OF_VAL.LANG_ID = 'ESN' AND S_LST_OF_VAL.ACTIVE_FLG = 'Y' AND S_LST_OF_VAL.NAME LIKE '%100%' AND S_LST_OF_VAL.HIGH IS NOT NULL) TIP_ID ON A.X_OCS_ID_TP_CD=TIP_ID.NAME
WHERE 1=1
    AND A.X_OCS_REF_NUM = '830062000'
;