------------------------ EXTRACCION PRODUCTOS ----------------------------------
SELECT 
B.PART_NUM AS CODIGO,
B.NAME AS NOMBRE,
A.ASSET_NUM AS NUMERO_PRODUCTO,
A.STATUS_CD AS ESTADO
FROM SIEBEL.S_ASSET A
LEFT JOIN SIEBEL.S_PROD_INT B ON A.PROD_ID = B.ROW_ID
WHERE 1 = 1
AND B.PART_NUM IN ('')
;

-- VALIDAR PRODUCTOS
SELECT B.PART_NUM AS CODIGO,B.NAME AS NOMBRE,A.ASSET_NUM AS NUMERO_PRODUCTO,A.STATUS_CD AS ESTADO, A.LAST_UPD AS FECHA_ACT
FROM SIEBEL.S_ASSET A
LEFT JOIN SIEBEL.S_PROD_INT B ON A.PROD_ID = B.ROW_ID
WHERE 1 = 1
AND A.ASSET_NUM IN ('260836499') -- Buscar por número de producto
;



--TODOS LOS PRODUCTOS PN
SELECT distinct
G.HIGH AS TIPO_DOC_PN,
e.X_OCS_ID_NUM AS DOCUMENTO,
B.PART_NUM AS CODIGO_PROD,
B.NAME AS NOMBRE,
A.ASSET_NUM AS NUM_PRODUCTO,
A.LAST_UPD AS FECHA_ACT,
S.DESC_TEXT AS ESTADO_PRODUCTO
FROM SIEBEL.S_ASSET A
LEFT JOIN SIEBEL.S_PROD_INT B ON A.PROD_ID = B.ROW_ID
LEFT JOIN SIEBEL.S_ASSET_X C ON A.ROW_ID = C.ROW_ID
LEFT JOIN SIEBEL.S_ASSET_CON D ON A.ROW_ID = D.ASSET_ID
LEFT JOIN SIEBEL.S_CONTACT E ON D.CONTACT_ID = E.ROW_ID
LEFT JOIN SIEBEL.S_ASSET_ACCNT F ON A.ROW_ID = F.ASSET_ID
LEFT JOIN SIEBEL.S_LST_OF_VAL G ON E.X_OCS_ID_TYPE = G.NAME
LEFT JOIN SIEBEL.S_LST_OF_VAL S ON A.STATUS_CD = S.NAME
WHERE 1 = 1
AND A.ASSET_NUM IN ('') -- Buscar por numero de producto
AND S.TYPE = 'IMPL_PHASE'
AND G.TYPE = 'OCS_NID_TYPES'
ORDER BY A.LAST_UPD DESC;

--TODOS LOS PRODUCTOS PJ
SELECT 
F.HIGH AS TIPO_DOC_PJ,
E.X_OCS_REF_NUM AS NUM_IDENT,
B.PART_NUM AS CODIGO_PROD,
B.NAME AS NOMBRE,
A.ASSET_NUM AS NUM_PRODUCTO,
C.LAST_UPD AS FECHA_ACT,
A.STATUS_CD AS ESTADO
FROM SIEBEL.S_ASSET A
LEFT JOIN SIEBEL.S_PROD_INT B ON A.PROD_ID = B.ROW_ID
LEFT JOIN SIEBEL.S_ASSET_X C ON A.ROW_ID = C.ROW_ID
LEFT JOIN SIEBEL.S_ASSET_ACCNT D ON A.ROW_ID = D.ASSET_ID
LEFT JOIN SIEBEL.S_ORG_EXT E ON D.ACCNT_ID = E.ROW_ID
LEFT JOIN SIEBEL.S_LST_OF_VAL F ON E.X_OCS_ID_TP_CD = F.NAME
WHERE 1 = 1
AND A.ASSET_NUM IN ('') -- Buscar por Numero de producto
AND F.TYPE = 'OCS_NID_TYPES'
ORDER BY A.LAST_UPD DESC;
