------------------------ EXTRACCION PRODUCTOS ----------------------------------
SELECT 
B.PROD_TP_CD AS CODIGO,
J.NAME AS NOMBRE,
A.ADMIN_CONTRACT_ID AS NUMERO_PRODUCTO,
B.CONTRACT_ST_TP_CD as ESTADO
FROM ADMMDM.CONTRACT A
LEFT JOIN ADMMDM.CONTRACTCOMPONENT B ON A.CONTRACT_ID = B.CONTRACT_ID
LEFT JOIN ADMMDM.CDADMINSYSTP I ON I.ADMIN_SYS_TP_CD = A.ADMIN_SYS_TP_CD
LEFT JOIN ADMMDM.CDPRODTP J ON B.PROD_TP_CD = J.PROD_TP_CD
WHERE 1=1
AND A.ADMIN_CONTRACT_ID IN ('50030040260',
'45030026392',
'00130115108',
'11330012730',
'00130213572')

AND J.NAME IS NOT NULL
ORDER BY A.LAST_UPDATE_DT DESC
;
------------------------ VALIDAR PRODUCTOS MDM ---------------------------------
SELECT DISTINCT
G.NAME AS T_DOC,
E.REF_NUM AS DOC,
--N.CONTACT_NAME AS NOMBRE,
LISTAGG(k.ROLE_TP_CD, ',') WITHIN GROUP (ORDER BY K.ROLE_TP_CD)AS MACROROL,
--D.NAME AS TIPO_RELACION,
B.PROD_TP_CD AS COD,
J.NAME AS NOMBRE_PRODUCTO,
A.ADMIN_CONTRACT_ID AS NUM_PROD,
F.NAME AS ESTADO_PRODUCTO
FROM ADMMDM.CONTRACT A
--LEFT JOIN ADMMDM.XCDACCTOFFCODETP Z ON A.XACCT_OFF_CODE_TP_CD = Z.ACCT_OFF_CODE_TP_CD
LEFT JOIN ADMMDM.CONTRACTCOMPONENT B ON A.CONTRACT_ID = B.CONTRACT_ID
LEFT JOIN ADMMDM.CONTRACTROLE C ON B.CONTR_COMPONENT_ID = C.CONTR_COMPONENT_ID
LEFT JOIN ADMMDM.IDENTIFIER E ON C.CONT_ID = E.CONT_ID
LEFT JOIN ADMMDM.CDCONTRACTSTTP F ON B.CONTRACT_ST_TP_CD = F.CONTRACT_ST_TP_CD
LEFT JOIN ADMMDM.CDIDTP G ON E.ID_TP_CD = G.ID_TP_CD
LEFT JOIN ADMMDM.CDPRODTP J ON B.PROD_TP_CD = J.PROD_TP_CD
LEFT JOIN ADMMDM.CONTMACROROLE K ON C.CONT_ID = K.CONT_ID
WHERE 1=1
AND A.ADMIN_CONTRACT_ID IN ('50030040260',
'45030026392',
'00130115108',
'11330012730',
'00130213572') -- Buscar por número de producto
GROUP BY G.NAME,E.REF_NUM,B.PROD_TP_CD,J.NAME,A.ADMIN_CONTRACT_ID,F.NAME
;

------------------ VALIDAR PERSONAS MDM ----------------------------------------
SELECT DISTINCT
G.NAME AS TIPO_DOC,
A.REF_NUM AS N_DOC, --Numero de documento
A.XNIT_CHECK_DIGIT AS DIGITO,
B.CONTACT_NAME AS NOMBRE,
D.NAME as MACROROL,
b.CLIENT_ST_TP_CD AS ESTADO,
B.LAST_UPDATE_DT AS FECHA_ACT, --Fecha actualización
b.LAST_UPDATE_USER,
F.NAME AS FUENTE
FROM ADMMDM.IDENTIFIER A
LEFT JOIN ADMMDM.CONTACT B ON A.CONT_ID = B.CONT_ID
LEFT JOIN ADMMDM.CONTMACROROLE C ON A.CONT_ID = C.CONT_ID
LEFT JOIN ADMMDM.CDROLETP D ON C.ROLE_TP_CD = D.ROLE_TP_CD
LEFT JOIN ADMMDM.CDIDTP G ON A.ID_TP_CD = G.ID_TP_CD
LEFT JOIN ADMMDM.CDSOURCEIDENTTP F ON B.SOURCE_IDENT_TP_CD = F.SOURCE_IDENT_TP_CD
WHERE 1=1
--AND D.NAME = 'Funcionario'
AND A.REF_NUM IN ('')  --Buscar por numero de documento
ORDER BY B.LAST_UPDATE_DT desc
;

----------------------- CORREO Y NUMERO ------------------------------------
SELECT DISTINCT
A.ID_TP_CD AS TIPO_DOC, --Tipo documento
A.REF_NUM AS N_DOC, --Numero de documento
B.CONTACT_NAME AS NOMBRE,
T.REF_NUM AS "CORREO/NUMERO",
DES.NAME AS TIPO_USO,
C.PREFERRED_IND AS PRINCIPAL,
T.LAST_UPDATE_DT
FROM ADMMDM.IDENTIFIER A
LEFT JOIN ADMMDM.CONTACT B ON A.CONT_ID = B.CONT_ID
LEFT JOIN ADMMDM.locationgroup C ON A.CONT_ID = C.CONT_ID
LEFT JOIN ADMMDM.CONTACTMETHODGROUP D ON C.LOCATION_GROUP_ID = D.LOCATION_GROUP_ID
LEFT JOIN ADMMDM.CONTACTMETHOD T ON D.CONTACT_METHOD_ID = T.CONTACT_METHOD_ID
LEFT JOIN ADMMDM.CDCONTMETHTP DES ON DES.CONT_METH_TP_CD = D.CONT_METH_TP_CD AND T.CONT_METH_CAT_CD = DES.CONT_METH_CAT_CD
WHERE 1=1
AND T.CONT_METH_CAT_CD = '1200000' -- Solo correos electronicos
--AND T.CONT_METH_CAT_CD = '1100000' -- Solo numeros de telefono
AND A.REF_NUM = '52736252'  --Buscar por numero de documento
ORDER BY T.REF_NUM ASC
;